export const dummyData = [
  {
    id: 1,
    name: "Document 1",
    link: "https://example.com/audio1.mp3",
    date: "2024-11-10",
    translation: "Translation of audio file 1",
  },
  {
    id: 2,
    name: "Document 2",
    link: "https://example.com/audio2.mp3",
    date: "2024-11-11",
    translation: "Translation of audio file 2",
  },
  {
    id: 3,
    name: "Document 3",
    link: "https://example.com/audio3.mp3",
    date: "2024-11-12",
    translation: "Translation of audio file 3",
  },
  {
    id: 4,
    name: "Document 4",
    link: "https://example.com/audio4.mp3",
    date: "2024-11-13",
    translation: "Translation of audio file 4",
  },
  {
    id: 5,
    name: "Document 5",
    link: "https://example.com/audio5.mp3",
    date: "2024-11-14",
    translation: "Translation of audio file 5",
  },
  {
    id: 6,
    name: "Document 6",
    link: "https://example.com/audio6.mp3",
    date: "2024-11-15",
    translation: "Translation of audio file 6",
  },
  {
    id: 7,
    name: "Document 7",
    link: "https://example.com/audio7.mp3",
    date: "2024-11-16",
    translation: "Translation of audio file 7",
  },
  {
    id: 8,
    name: "Document 8",
    link: "https://example.com/audio8.mp3",
    date: "2024-11-17",
    translation: "Translation of audio file 8",
  },
  {
    id: 9,
    name: "Document 9",
    link: "https://example.com/audio9.mp3",
    date: "2024-11-18",
    translation: "Translation of audio file 9",
  },
  {
    id: 10,
    name: "Document 10",
    link: "https://example.com/audio10.mp3",
    date: "2024-11-19",
    translation: "Translation of audio file 10",
  },
];
